export type PermissionCode = 
| "users.manage"
| "inventory.read"
| "inventory.write"
| "inventory.reserve"
| "crm.read"
| "crm.write"
| "sales.read"
| "sales.create_offer"
| "sales.complete"
| "reports.read"