import { expect, test } from '@playwright/test'
import { login } from './helpers'

test('completes the customer-to-sale dealership workflow', async ({ page }) => {
  test.setTimeout(120_000)
  const marker = Date.now().toString().slice(-8)
  const customerName = `E2E Buyer ${marker}`
  const stockNumber = `E2E-${marker}`
  const selectContaining = async (label: string, text: string) => {
    const escapedLabel = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const select = page.locator('label').filter({ hasText: new RegExp(`^${escapedLabel}`) }).locator('select').first()
    const value = await select.locator('option').filter({ hasText: text }).getAttribute('value')
    expect(value).not.toBeNull()
    await select.selectOption(value!)
  }

  await login(page)

  await page.goto('/customers')
  await page.getByRole('button', { name: '+ Add customer' }).click()
  await page.getByLabel('First Name').fill('E2E')
  await page.getByLabel('Last Name').fill(`Buyer ${marker}`)
  await page.getByLabel('Email').fill(`e2e.${marker}@example.test`)
  await page.getByLabel('Phone', { exact: true }).fill(`+361${marker}`)
  await page.getByLabel('City').fill('Budapest')
  await page.getByRole('button', { name: 'Create customer' }).click()
  await expect(page.getByText('Customer created.')).toBeVisible()
  const customerRow = page.getByRole('row').filter({ hasText: customerName })
  await customerRow.getByRole('combobox').selectOption('CUSTOMER')
  await expect(page.getByText('Customer status updated.')).toBeVisible()

  await page.goto('/inventory/new')
  await page.getByLabel('Stock Number').fill(stockNumber)
  await page.getByLabel('Make').fill('Thesis Motors')
  await page.getByLabel('Model', { exact: true }).fill('Monolith')
  await page.getByLabel('Model Year').fill('2026')
  await page.getByLabel('Mileage Km').fill('10')
  await page.getByLabel('Purchase Price').fill('20000')
  await page.getByLabel('Asking Price').fill('26000')
  await page.getByLabel('Minimum Price').fill('23000')
  await page.getByRole('button', { name: 'Create vehicle' }).click()
  await expect(page).toHaveURL(/\/inventory\/\d+$/)
  const vehicleUrl = page.url()
  await page.getByRole('combobox').last().selectOption('AVAILABLE')
  await expect(page.getByText('Vehicle status updated.')).toBeVisible()

  await page.goto('/leads/new')
  await page.getByLabel('Customer').selectOption({ label: customerName })
  await page.getByLabel('Priority').selectOption('HIGH')
  await page.getByLabel('Minimum budget').fill('23000')
  await page.getByLabel('Maximum budget').fill('30000')
  await page.getByLabel('Notes').fill('Created by the repeatable E2E benchmark.')
  await page.getByRole('button', { name: 'Create lead' }).click()
  await expect(page).toHaveURL(/\/leads\/\d+$/)
  const leadUrl = page.url()
  await page.getByLabel('Subject').fill('Initial qualification')
  await page.getByLabel('Details').fill('Customer requirements captured.')
  await page.getByRole('button', { name: 'Add activity' }).click()
  await expect(page.getByText('Activity added.')).toBeVisible()
  await page.getByPlaceholder('Interest notes (optional)').fill('Primary E2E interest')
  await page.getByRole('button', { name: 'Add vehicle' }).click()
  await expect(page.getByText('Vehicle interest added.')).toBeVisible()

  await page.goto('/test-drives')
  await page.getByRole('button', { name: '+ Schedule test drive' }).click()
  await page.getByLabel('Customer').selectOption({ label: customerName })
  await selectContaining('Vehicle', stockNumber)
  await selectContaining('Related lead (optional)', customerName)
  const start = new Date(Date.now() + 120 * 86_400_000 + Number(marker.slice(-4)) * 60_000)
  const end = new Date(start.getTime() + 3_600_000)
  const localDateTime = (date: Date) => {
    const shifted = new Date(date.getTime() - date.getTimezoneOffset() * 60_000)
    return shifted.toISOString().slice(0, 16)
  }
  await page.getByLabel('Starts').fill(localDateTime(start))
  await page.getByLabel('Ends').fill(localDateTime(end))
  await page.getByRole('button', { name: 'Schedule test drive' }).click()
  await expect(page.getByText('Test drive scheduled.')).toBeVisible()

  await page.goto('/offers/new')
  await selectContaining('Related lead (optional)', customerName)
  await selectContaining('Vehicle', stockNumber)
  await page.getByLabel('Vehicle Price').fill('25500')
  await page.getByLabel('Discount Amount').fill('500')
  await page.getByLabel('Tax Amount').fill('5000')
  await page.getByLabel('Fee Amount').fill('250')
  await page.getByRole('button', { name: 'Create draft offer' }).click()
  await expect(page).toHaveURL(/\/offers\/\d+$/)
  const offerStatus = page.getByRole('combobox')
  await offerStatus.selectOption('SENT')
  await page.getByRole('button', { name: 'Save status' }).click()
  await expect(page.getByText('Offer status updated.')).toBeVisible()
  await offerStatus.selectOption('ACCEPTED')
  await page.getByRole('button', { name: 'Save status' }).click()
  await expect(page.getByText('Offer status updated.')).toBeVisible()

  await page.goto(vehicleUrl)
  await page.getByLabel('Customer').selectOption({ label: customerName })
  await page.getByLabel('Expires at').fill(localDateTime(new Date(Date.now() + 7 * 86_400_000)))
  await page.getByLabel('Agreed price').fill('25000')
  await page.getByRole('button', { name: 'Reserve', exact: true }).click()
  await expect(page.getByText('Vehicle reserved.')).toBeVisible()

  await page.goto('/sales/new')
  await selectContaining('Active reservation (optional)', customerName)
  await page.getByLabel('Vehicle Price').fill('25000')
  await page.getByLabel('Tax Amount').fill('5000')
  await page.getByRole('button', { name: 'Create pending sale' }).click()
  await expect(page).toHaveURL(/\/sales\/\d+$/)
  const finalizeForm = page.locator('form').filter({ hasText: 'Finalize sale' })
  await expect(finalizeForm.getByRole('heading', { name: 'Finalize sale' })).toBeVisible()
  await finalizeForm.getByRole('combobox').selectOption('COMPLETED')
  await page.getByRole('button', { name: 'Complete sale' }).click()
  await expect(page.getByText('Sale completed and vehicle marked sold.')).toBeVisible()

  await page.goto(leadUrl)
  await expect(page.getByRole('heading', { name: customerName })).toBeVisible()
})
